### ISSUE TITLE
Snow potion reward appears do do nothing upon quaffing

### ISSUE THREAD

**Issue by skidznet** [airbreather/cacophony-inc#10]

**Comment by airbreather** [comment]
Fixed in 1.0.2.

**Comment by skidznet** [comment]
for some reason these don't work again.  splashing them does nothing.

**Comment by airbreather** [comment]
I may have figured this one out... the log is whining that [potion ID 40](https://github.com/airbreather/cacophony-inc/blob/c099ea3a861ee86ab6cf6e665cfab5c564c48c37/data/config/witchery.cfg#L166) is already taken up by `potion.featherfall` (not `witchery:potion.featherfall`, mind you).

**Comment by airbreather** [comment]
BAH, EnhancedPortals registers its own PotionFeatherfall with a hardcoded 40.  What a jerk.

We can edit Witchery's config to make this better, at least.  [This guy](https://github.com/GTNewHorizons/NewHorizons/issues/375) set his .chilled to 88.  Might as well do the same.

**Comment by airbreather** [comment]
@skidznet I just walked over to your computer and followed these steps on the FTB version of 1.0.2:
1. Start Minecraft through the FTB Launcher using whatever advanced options you had set up.
2. Once it starts, click Single Player.
3. Apply the usual settings: Creative mode, BoP, seed "Find your Voice".
4. Create the world.
5. Once you have control of your character, use `/hqm edit` to get the OP quest book.
6. Shift + Left-click on the jerky quest and all its prerequisites.
7. Left-click on the jerky quest, select any of the pick-one rewards, and claim it.
8. Move to a spot where there's no snow around.
9. Drop out to survival mode (`/gamemode s`).
10. Throw one of the potions on the ground at your feet.

As expected, snow appears at your feet, and you get the buff.

Remember, snow won't show up on top of a grass dirt block if there's already something on top of it like the "growing" kind of grass.

Closing this again.

**Comment by airbreather** [comment]
Reopening yet again -- it doesn't work on our little server thing we've got going on.  Ugh.
