### ISSUE TITLE
Uncommon Bag

### ISSUE THREAD

**Issue by airbreather** [airbreather/cacophony-inc#18]
Looks like there's still a bag that's just called "Uncommon Bag".

**Comment by skidznet** [comment]
aren't they called uncommon reward by default?  if that is the case, then that would make this a named bag.  It might contain the thaumcraft uncommon treasure bag.

**Comment by airbreather** [comment]
You're right, I completely forgot about this one (I think I said this exact thing during our final pre-release review). Never mind.
